### PR TITLE
Entity pick control cancelation

### PR DESCRIPTION
**Pull request by LatzekLat**
Code proposal that fixes few issues:
1) Pick entity button toggle state is not changed after entity picked
2) It is not possible to cancel pick process(in ScriptCanvas 'Variable')

### CODE REVIEW

**Comment by ranilianaws** [comment]
Hello @LatzekLat ,
Thank you for the contribution! We will evaluate the code and get back to you as soon as possible.

**Comment by ranilianaws** [comment]
Hello @LatzekLat ,

Can you please re-evaluate this issue against 1.13? I believe this was fixed without the code change.

**Comment by LatzekLat** [comment]
Hello @ranilianaws ,
Have tried it on clear LY 1.13 installation. Problem seems still present unfortunately.

**Comment by ranilianaws** [comment]
Hello @LatzekLat ,

This has been fixed in the next release of LY. Thank you for the contribution.

**Pull request closed without merging**
