### PR TITLE
Support map with string key serialization

### PR DESCRIPTION
**Pull request by rustamserg**
Fix serialization of map container with string type as key

### CODE REVIEW

**Comment by AMZN-puvvadar** [comment]
Hi @rustamserg ,

Can you describe the original issue here in some more detail? What was the serialization error that was seen?

**Comment by dkondrashkin** [comment]
Hi, @AMZN-puvvadar,

We've encountered an issue with map container deserialization - it did not work for maps using ```string``` type as a key. In this case compiler has always chosen first ```Serialize(...)``` function overload (accepting ```std::pair<K, V>&``` argument) which, in turn, resulted in an empty map instance. Then we discovered that  second overload treats string keys in a different, yet working way. So we've came up with this fix.

**Comment by AMZN-puvvadar** [comment]
Thanks @dkondrashkin ,

We've started review of this submission.

**Comment by AMZN-puvvadar** [comment]
@dkondrashkin @rustamserg ,

We've accepted this change, thanks again for the submission!

**Pull request closed without merging**
