### PR TITLE
OnAssetReady support changing of queue slice instantiation

### PR DESCRIPTION
**Pull request by rustamserg**
In some cases OnAssertReady starts iterating on container during its modification. Thus we have to use find_if instead of iteration

### CODE REVIEW

**Comment by AMZN-puvvadar** [comment]
Hi @rustamserg ,

Is there a purpose to the while(true) part of this change? It seems find_if by itself should handle all prior functionality captured by the iterating loop.

**Comment by AMZN-puvvadar** [comment]
Hi @rustamserg ,

We've started evaluation of this. Are there any repro steps you could provide?

**Comment by rustamserg** [comment]
This problem is caused by our content and the way we use asset system. Extract clean repo is really hard however I will try to explain our motivation to share the change:

- OnAssertReady contains iteration over internal container
- During the iteration external source code is called
- The external call can change the internal container on the same callstack during iteration

We can avoid this problem on caller side but we believe that caller should not know about entity context internal logic so we decided to rewrite iteration in the way that stable to container modifications.

**Comment by AMZN-puvvadar** [comment]
Hi @rustamserg ,

Thanks for the details, this is very helpful. We've started review for this.

**Comment by AMZN-puvvadar** [comment]
Hi @rustamserg ,

We've accepted this change, thanks for the submission!

**Pull request closed without merging**
