### PR TITLE
89) Add EntityId_FromString utility function for EntityId.

### PR DESCRIPTION
**Pull request by tkgdhughes**
### Description 

As title, a trivial addition to add a utility function to EntityId.

### CODE REVIEW

**Comment by ranilianaws** [comment]
Hey @tkgdhughes ,

Thanks for the contribution. We will evaluate the code and get back to you soon.

**Comment by ranilianaws** [comment]
Hey @tkgdhughes ,

Can you tell us more about the use case? Why not use the exposed entity ID type instead?

**Comment by tkgdhughes** [comment]
Hey @ranilianaws, 

I've just been digging back through the usage and I _think_ that this code was written prior to EntityId having a GridMate marshaler. I imagine there was a string marshaler available, so the EntityId which needed sending was forced ToString then back FromString at the other end. I'm wondering if there is any useful use case for FromString anymore now that there is a valid EntityId marshaler. I suppose just from an API symmetry point of view there is a ToString, so a FromString may be useful somewhere.

**Comment by ranilianaws** [comment]
Hey @tkgdhughes ,

Thanks for the contribution but we will not take this change as we don't see a reason to support this functionality.

**Pull request closed without merging**
