### PR TITLE
103) Added a modal popup when the application descriptor can't be found.

### PR DESCRIPTION
**Pull request by tkgdhughes**
### Description

Upgraded the silent failure and printf to a modal popup when the dedicated server fails to find `dev\<game>\config\game.xml`

### CODE REVIEW

**Comment by AMZN-alexpete** [comment]
Hey @tkgdhughes,

Thank you for the contribution. We will evaluate the code and get back to you soon.

**Comment by AMZN-puvvadar** [comment]
Hey @tkgdhughes,

I'll be handling the review of this. One initial question, when you mention "the silent failure" do you mean that the fprintf is easily missed or is there something else?

**Comment by tkgdhughes** [comment]
Morning @AMZN-alexpete,
Yes thanks, that is correct.  On reading it back I appreciate that the description could be more clear.
Thanks

**Comment by AMZN-puvvadar** [comment]
Hey @tkgdhughes,

We've accepted this change, thanks for the submit!

**Pull request closed without merging**
